[build]
  publish = "."
  command = "bash build.sh"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/schemas"
  to = "/.netlify/functions/schemas"
  status = 200

[[redirects]]
  from = "/api/schema/*"
  to = "/.netlify/functions/schema"
  status = 200

[[redirects]]
  from = "/api/fastas"
  to = "/.netlify/functions/fastas"
  status = 200

[[redirects]]
  from = "/api/fasta/*"
  to = "/.netlify/functions/fasta"
  status = 200
